# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='0011ff.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('native_name', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='0011ff.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Language')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Period')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='0011ff.png', upload_to='')),
                ('periods', models.ManyToManyField(related_name='periods', to='dashboard.Period')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Language')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='contenttr',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Language'),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topictr',
            unique_together=set([('language', 'topic')]),
        ),
        migrations.AlterUniqueTogether(
            name='periodtr',
            unique_together=set([('language', 'period')]),
        ),
        migrations.AlterUniqueTogether(
            name='contenttr',
            unique_together=set([('language', 'content')]),
        ),
    ]
