# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170323_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
    ]
