# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170323_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttr',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contenttr',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='periodtr',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='topictr',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
