# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170406_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='periods',
            field=models.ManyToManyField(default=[], related_name='periods', to='dashboard.Period'),
        ),
    ]
