# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170412_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='periods',
            field=models.ManyToManyField(related_name='periods', to='dashboard.Period'),
        ),
    ]
