# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170207_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='0011ff.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='period',
            name='image',
            field=models.ImageField(default='0011ff.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='0011ff.png', upload_to=''),
        ),
    ]
